[build]
  base = "app/frontend"
  command = "npm ci && npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000

[context.production]
  environment = { NODE_ENV = "production" }
  command = "npm ci && npm run build"

[context.deploy-preview]
  environment = { NODE_ENV = "development" }
